const buildings = [
	{
		"id": "1",
		"Colonia": "Lomas de San Ángel Inn",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "4054",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "24-Jul-15",
		"Número de viviendas": "40",
		"Número de niveles de la construcción": "6",
		"Superficie m2": "2054.12",
		"Superficie máxima de construcción m2": "5751.54",
		"Número de árboles talados": "7",
		"Fusión de Predios": "Si",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "136",
		"Litros de agua": "20400",
		"Número de autos por construcción": "25.6",
		"Latitud": "19.347106499999999",
		"Longitud": "-99.202454999999901"
	},
	{
		"id": "2",
		"Colonia": "Lomas de San Ángel Inn",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "4058",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "8",
		"Número de niveles de la construcción": "5",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "27.2",
		"Litros de agua": "4080",
		"Número de autos por construcción": "5.12",
		"Latitud": "19.347106499999999",
		"Longitud": "-99.202454999999901"
	},
	{
		"id": "3",
		"Colonia": "Atlamaya",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "4052",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "26-Jun-15",
		"Número de viviendas": "40",
		"Número de niveles de la construcción": "6",
		"Superficie m2": "2054.12",
		"Superficie máxima de construcción m2": "5751.54",
		"Número de árboles talados": "7",
		"Fusión de Predios": "Si",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "136",
		"Litros de agua": "20400",
		"Número de autos por construcción": "25.6",
		"Latitud": "19.347239116960999",
		"Longitud": "-99.204219532155705"
	},
	{
		"id": "4",
		"Colonia": "Atlamaya",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "411",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "S/D",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.347239116960999",
		"Longitud": "-99.204219532155705"
	},
	{
		"id": "5",
		"Colonia": "Prograso Tizapán",
		"Calle": "Boulevard Adolfo López Mateos",
		"Número": "125",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "20-Jun-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "16",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "15",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.333434063720102",
		"Longitud": "-99.209324656778307"
	},
	{
		"id": "6",
		"Colonia": "Olivar de los Padres",
		"Calle": "Rómulo O´Farril ",
		"Número": "468",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "187",
		"Número de niveles de la construcción": "18",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "5178",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "22",
		"Especificaciones": "S/D",
		"Población aproximada": "635.79999999999995",
		"Litros de agua": "95370",
		"Número de autos por construcción": "119.68",
		"Latitud": "19.3416516903672",
		"Longitud": "-99.206134992688902"
	},
	{
		"id": "7",
		"Colonia": "Prograso Tizapán",
		"Calle": "Yucatán ",
		"Número": "18",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "18-Nov-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "3",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "1196.3900000000001",
		"Número de árboles talados": "2",
		"Fusión de Predios": "Si",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "Área de Conservación Patrimonial",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338270000000001",
		"Longitud": "-99.198699999999903"
	},
	{
		"id": "8",
		"Colonia": "Rancho San Francisco del Pueblo de San Bartolo Ameyalco",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5969",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "12-Sep-16",
		"Número de viviendas": "8",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "2",
		"Especificaciones": "S/D",
		"Población aproximada": "27.2",
		"Litros de agua": "4080",
		"Número de autos por construcción": "5.12",
		"Latitud": "19.3379531802983",
		"Longitud": "-99.245779327978795"
	},
	{
		"id": "9",
		"Colonia": "Ampliación las Águilas",
		"Calle": "Colina",
		"Número": "93",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "33",
		"Número de niveles de la construcción": "7",
		"Superficie m2": "4055.04",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "112.2",
		"Litros de agua": "16830",
		"Número de autos por construcción": "21.12",
		"Latitud": "19.346591009828298",
		"Longitud": "-99.222620420623102"
	},
	{
		"id": "10",
		"Colonia": "San Agustín del Pueblo de Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "4373",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "20-Jul-15",
		"Número de viviendas": "66",
		"Número de niveles de la construcción": "15",
		"Superficie m2": "660.8",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "8",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "15",
		"Especificaciones": "S/D",
		"Población aproximada": "224.4",
		"Litros de agua": "33660",
		"Número de autos por construcción": "42.24",
		"Latitud": "19.3427977801712",
		"Longitud": "-99.223633423501397"
	},
	{
		"id": "11",
		"Colonia": "San Agustín del Pueblo de Tetelpan",
		"Calle": "Minas",
		"Número": "7",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "24-Jul-15",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "6",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.345076492035499",
		"Longitud": "-99.222582285704604"
	},
	{
		"id": "12",
		"Colonia": "San Agustín del Pueblo de Tetelpan",
		"Calle": "Camino Real a Tetelpan",
		"Número": "193",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "10",
		"Número de niveles de la construcción": "3",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "34",
		"Litros de agua": "5100",
		"Número de autos por construcción": "6.4",
		"Latitud": "19.3429687194952",
		"Longitud": "-99.222457328089504"
	},
	{
		"id": "13",
		"Colonia": "San Agustín del Pueblo de Tetelpan",
		"Calle": "Río de Guadalupe",
		"Número": "21",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "16-Jun-16",
		"Número de viviendas": "20",
		"Número de niveles de la construcción": "6",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "6",
		"Especificaciones": "S/D",
		"Población aproximada": "68",
		"Litros de agua": "10200",
		"Número de autos por construcción": "12.8",
		"Latitud": "19.345076492035499",
		"Longitud": "-99.222582285704604"
	},
	{
		"id": "14",
		"Colonia": "San Agustín del Pueblo de Tetelpan",
		"Calle": "Minas ",
		"Número": "17",
		"Uso de Suelo": "Habitacional ",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "30",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "6",
		"Especificaciones": "S/D",
		"Población aproximada": "102",
		"Litros de agua": "15300",
		"Número de autos por construcción": "19.2",
		"Latitud": "19.345076492035499",
		"Longitud": "-99.222582285704604"
	},
	{
		"id": "15",
		"Colonia": "San Agustín del Pueblo de Tetelpan",
		"Calle": "Minas",
		"Número": "35",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "40",
		"Número de niveles de la construcción": "6",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "5865.31",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "6",
		"Especificaciones": "S/D",
		"Población aproximada": "136",
		"Litros de agua": "20400",
		"Número de autos por construcción": "25.6",
		"Latitud": "19.345076492035499",
		"Longitud": "-99.222582285704604"
	},
	{
		"id": "16",
		"Colonia": "San Agustín del Pueblo de Tetelpan",
		"Calle": "Camino Real de Minas",
		"Número": "4375",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "10-Aug-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "15",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.345076492035499",
		"Longitud": "-99.222582285704604"
	},
	{
		"id": "17",
		"Colonia": "San Agustín del Pueblo de Tetelpan",
		"Calle": "Camino Real de Tetelpan",
		"Número": "90",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "21-Oct-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.345076492035499",
		"Longitud": "-99.222582285704604"
	},
	{
		"id": "18",
		"Colonia": "San Agustín del Pueblo de Tetelpan",
		"Calle": "Camino Real de Tetelpan",
		"Número": "104",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "27-Oct",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.345076492035499",
		"Longitud": "-99.222582285704604"
	},
	{
		"id": "19",
		"Colonia": "Tizampano",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "4602",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "30-Jan-14",
		"Número de viviendas": "15",
		"Número de niveles de la construcción": "5",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "3810",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "5",
		"Especificaciones": "S/D",
		"Población aproximada": "51",
		"Litros de agua": "7650",
		"Número de autos por construcción": "9.6",
		"Latitud": "19.338205500000001",
		"Longitud": "-99.244849500000001"
	},
	{
		"id": "20",
		"Colonia": "Tizampano",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "4620",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "15",
		"Número de niveles de la construcción": "6",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "51",
		"Litros de agua": "7650",
		"Número de autos por construcción": "9.6",
		"Latitud": "19.338205500000001",
		"Longitud": "-99.244849500000001"
	},
	{
		"id": "21",
		"Colonia": "Tizampano",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "4694",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "23-Jun",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "3",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338205500000001",
		"Longitud": "-99.244849500000001"
	},
	{
		"id": "22",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5410",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "24-Jul-15",
		"Número de viviendas": "1",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "3",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "3.4",
		"Litros de agua": "510",
		"Número de autos por construcción": "0.64",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "23",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5344",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "24-Jul-15",
		"Número de viviendas": "23",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "2776.5120000000002",
		"Superficie máxima de construcción m2": "2782.248",
		"Número de árboles talados": "2",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "78.2",
		"Litros de agua": "11730",
		"Número de autos por construcción": "14.72",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "24",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5438",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "24-Jul-15",
		"Número de viviendas": "23",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "2625.6",
		"Superficie máxima de construcción m2": "2674.308",
		"Número de árboles talados": "4",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "78.2",
		"Litros de agua": "11730",
		"Número de autos por construcción": "14.72",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "25",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5350",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "24-Jul-15",
		"Número de viviendas": "27",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "3265.64",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "91.8",
		"Litros de agua": "13770",
		"Número de autos por construcción": "17.28",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "26",
		"Colonia": "Tetelpan",
		"Calle": "Privada San Miguel",
		"Número": "19",
		"Uso de Suelo": "Habitacional ",
		"Fecha de denuncia": "24-Jul-15",
		"Número de viviendas": "8",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "2598",
		"Superficie máxima de construcción m2": "2880",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "2",
		"Especificaciones": "S/D",
		"Población aproximada": "27.2",
		"Litros de agua": "4080",
		"Número de autos por construcción": "5.12",
		"Latitud": "19.338548711611601",
		"Longitud": "-99.236009982428499"
	},
	{
		"id": "27",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5138",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "24-Jul-15",
		"Número de viviendas": "23",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "1535.04",
		"Superficie máxima de construcción m2": "1563.856",
		"Número de árboles talados": "1",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "78.2",
		"Litros de agua": "11730",
		"Número de autos por construcción": "14.72",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "28",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "4790",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "24-Jul-15",
		"Número de viviendas": "60",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "5928.3",
		"Superficie máxima de construcción m2": "6227.2",
		"Número de árboles talados": "2",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "204",
		"Litros de agua": "30600",
		"Número de autos por construcción": "38.4",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "29",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5317",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "24-Jul-15",
		"Número de viviendas": "31",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "2650",
		"Superficie máxima de construcción m2": "3710",
		"Número de árboles talados": "6",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "105.39999999999999",
		"Litros de agua": "15809.999999999998",
		"Número de autos por construcción": "19.84",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "30",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5016",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "10-Dec-15",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "31",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5760",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Jan-16",
		"Número de viviendas": "35",
		"Número de niveles de la construcción": "8",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "159",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "Posibilidad de derrumbe",
		"Población aproximada": "119",
		"Litros de agua": "17850",
		"Número de autos por construcción": "22.400000000000002",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "32",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5886",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "24-Feb-16",
		"Número de viviendas": "47",
		"Número de niveles de la construcción": "7",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "159.79999999999998",
		"Litros de agua": "23969.999999999996",
		"Número de autos por construcción": "30.080000000000002",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "33",
		"Colonia": "Tetelpan",
		"Calle": "Jazmín",
		"Número": "13",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.352296180249699",
		"Longitud": "-99.235205840442305"
	},
	{
		"id": "34",
		"Colonia": "Tetelpan",
		"Calle": "Encino Grannde",
		"Número": "13",
		"Uso de Suelo": "Habitacional ",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "8",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "2604.58",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "5",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "2",
		"Especificaciones": "S/D",
		"Población aproximada": "27.2",
		"Litros de agua": "4080",
		"Número de autos por construcción": "5.12",
		"Latitud": "19.3390591242478",
		"Longitud": "-99.232846659822897"
	},
	{
		"id": "35",
		"Colonia": "San Agustín del Pueblo de Tetelpan",
		"Calle": "Callejón de Minas ",
		"Número": "73",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "12",
		"Número de niveles de la construcción": "3",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "26",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "40.799999999999997",
		"Litros de agua": "6120",
		"Número de autos por construcción": "7.68",
		"Latitud": "19.344131999999998",
		"Longitud": "-99.219523499999994"
	},
	{
		"id": "36",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "4407",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "3",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "37",
		"Colonia": "San Agustín del Pueblo de Tetelpan",
		"Calle": "Camino Real a Tetelpan",
		"Número": "164",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "18",
		"Número de niveles de la construcción": "3",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "10 anomalías de alta resistividad",
		"Población aproximada": "61.199999999999996",
		"Litros de agua": "9180",
		"Número de autos por construcción": "11.52",
		"Latitud": "19.3429687194952",
		"Longitud": "-99.222457328089504"
	},
	{
		"id": "38",
		"Colonia": "Tizampano",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5300",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "80",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "4478.2",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "36",
		"Fusión de Predios": "Si",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "272",
		"Litros de agua": "40800",
		"Número de autos por construcción": "51.2",
		"Latitud": "19.338205500000001",
		"Longitud": "-99.244849500000001"
	},
	{
		"id": "39",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5317",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "31",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "6",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "105.39999999999999",
		"Litros de agua": "15809.999999999998",
		"Número de autos por construcción": "19.84",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "40",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5316",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "18",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "4",
		"Fusión de Predios": "Si",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "41",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "1310",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "10-Aug-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "Trabajos de demolición",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "42",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5414",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "18-Oct-16",
		"Número de viviendas": "27",
		"Número de niveles de la construcción": "3",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "91.8",
		"Litros de agua": "13770",
		"Número de autos por construcción": "17.28",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "43",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5436",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "1",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "44",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "4375",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "22-Sep-15",
		"Número de viviendas": "32",
		"Número de niveles de la construcción": "7",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "31",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "15",
		"Especificaciones": "S/D",
		"Población aproximada": "108.8",
		"Litros de agua": "16320",
		"Número de autos por construcción": "20.48",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "45",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5497",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "21-Oct-16",
		"Número de viviendas": "20",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "2",
		"Fusión de Predios": "Si",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "68",
		"Litros de agua": "10200",
		"Número de autos por construcción": "12.8",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "46",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5049",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "21-Oct-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "2",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "47",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "4415",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "21-Oct-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "Trabajos de demolición",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "48",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5410",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "15-Nov-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "Sellos de Clausura ",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "49",
		"Colonia": "Tetelpan",
		"Calle": "Magnolia ",
		"Número": "16",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "19-Dec-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.332670759789998",
		"Longitud": "-99.249597982842104"
	},
	{
		"id": "50",
		"Colonia": "Tetelpan",
		"Calle": "Magnolia ",
		"Número": "16",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "9-Feb-17",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.332670759789998",
		"Longitud": "-99.249597982842104"
	},
	{
		"id": "51",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "1338",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "13-Jun-17",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "52",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "4526",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "19-Jun-17",
		"Número de viviendas": "46",
		"Número de niveles de la construcción": "7",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "156.4",
		"Litros de agua": "23460",
		"Número de autos por construcción": "29.44",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "53",
		"Colonia": "Tetelpan",
		"Calle": "Encino Grande",
		"Número": "51",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "19-Oct-17",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "2",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.3390591242478",
		"Longitud": "-99.232846659822897"
	},
	{
		"id": "54",
		"Colonia": "Tetelpan",
		"Calle": "Flores",
		"Número": "10",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "18-Jan-18",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "1",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "S/D",
		"Especificaciones": "No cuenta con Registro de manifestación de construcción ",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.340251464115699",
		"Longitud": "-99.235261039026696"
	},
	{
		"id": "55",
		"Colonia": "Tetelpan",
		"Calle": "Encino Grande",
		"Número": "51",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "15-Feb-18",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "2",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.3390591242478",
		"Longitud": "-99.232846659822897"
	},
	{
		"id": "56",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5016",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "14-Mar-18",
		"Número de viviendas": "25",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "85",
		"Litros de agua": "12750",
		"Número de autos por construcción": "16",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "57",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5342",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "7-Apr-18",
		"Número de viviendas": "19",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "64.599999999999994",
		"Litros de agua": "9690",
		"Número de autos por construcción": "12.16",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "58",
		"Colonia": "Tetelpan",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "1195",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "4-Nov-18",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "S/D",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338856564487202",
		"Longitud": "-99.234792660523794"
	},
	{
		"id": "59",
		"Colonia": "Olivar de los Padres",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5602",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "20-Jul-15",
		"Número de viviendas": "60",
		"Número de niveles de la construcción": "15",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "11",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "204",
		"Litros de agua": "30600",
		"Número de autos por construcción": "38.4",
		"Latitud": "19.338205500000001",
		"Longitud": "-99.244849500000001"
	},
	{
		"id": "60",
		"Colonia": "Olivar de los Padres",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5760",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "20-Jul-15",
		"Número de viviendas": "35",
		"Número de niveles de la construcción": "7",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "159",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "Posibilidad de dedrrumbe",
		"Población aproximada": "119",
		"Litros de agua": "17850",
		"Número de autos por construcción": "22.400000000000002",
		"Latitud": "19.338205500000001",
		"Longitud": "-99.244849500000001"
	},
	{
		"id": "61",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "481",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "20-Jul-15",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "Sellos de clausura ",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "62",
		"Colonia": "Olivar de los Padres",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5714",
		"Uso de Suelo": "Habitacional ",
		"Fecha de denuncia": "20-Jul-15",
		"Número de viviendas": "6",
		"Número de niveles de la construcción": "3",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "4",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "20.399999999999999",
		"Litros de agua": "3060",
		"Número de autos por construcción": "3.84",
		"Latitud": "19.338205500000001",
		"Longitud": "-99.244849500000001"
	},
	{
		"id": "63",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "669",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Jan-16",
		"Número de viviendas": "184",
		"Número de niveles de la construcción": "7",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "110",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "625.6",
		"Litros de agua": "93840",
		"Número de autos por construcción": "117.76",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "64",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "1076",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Jan-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "65",
		"Colonia": "Olivar de los Padres",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5602",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "19-Jan-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "15",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "11",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338205500000001",
		"Longitud": "-99.244849500000001"
	},
	{
		"id": "66",
		"Colonia": "Olivar de los Padres",
		"Calle": "Glaciar",
		"Número": "720",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "2-May-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.3352013425826",
		"Longitud": "-99.232296392895407"
	},
	{
		"id": "67",
		"Colonia": "Lomas de San Ángel Inn",
		"Calle": "Avenida Toluca",
		"Número": "187",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "20-Jun-16",
		"Número de viviendas": "10",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "34",
		"Litros de agua": "5100",
		"Número de autos por construcción": "6.4",
		"Latitud": "19.337824879097099",
		"Longitud": "-99.222579731972303"
	},
	{
		"id": "68",
		"Colonia": "Olivar de los Padres",
		"Calle": "Calzada Olivar de los Padres",
		"Número": "986",
		"Uso de Suelo": "Habitacional ",
		"Fecha de denuncia": "1-Jul-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.3341645",
		"Longitud": "-99.230625000000003"
	},
	{
		"id": "69",
		"Colonia": "Olivar de los Padres",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5886",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "47",
		"Número de niveles de la construcción": "7",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "159.79999999999998",
		"Litros de agua": "23969.999999999996",
		"Número de autos por construcción": "30.080000000000002",
		"Latitud": "19.338205500000001",
		"Longitud": "-99.244849500000001"
	},
	{
		"id": "70",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Olivar de los Padre",
		"Número": "1118",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "23",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "2965.47",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "7",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "78.2",
		"Litros de agua": "11730",
		"Número de autos por construcción": "14.72",
		"Latitud": "19.34027",
		"Longitud": "-99.214479999999895"
	},
	{
		"id": "71",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "949",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "35",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "3889",
		"Superficie máxima de construcción m2": "4900",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "119",
		"Litros de agua": "17850",
		"Número de autos por construcción": "22.400000000000002",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "72",
		"Colonia": "Olivar de los Padres",
		"Calle": "Calzada Olivar de los Padres",
		"Número": "818",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "1",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.3341645",
		"Longitud": "-99.230625000000003"
	},
	{
		"id": "73",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "518",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "6",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "Sellos de clausura ",
		"Población aproximada": "20.399999999999999",
		"Litros de agua": "3060",
		"Número de autos por construcción": "3.84",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "74",
		"Colonia": "Olivar de los Padres",
		"Calle": "Calzada Olivar de los Padres",
		"Número": "850",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "27",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "3402.89",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "91.8",
		"Litros de agua": "13770",
		"Número de autos por construcción": "17.28",
		"Latitud": "19.3341645",
		"Longitud": "-99.230625000000003"
	},
	{
		"id": "75",
		"Colonia": "Olivar de los Padres",
		"Calle": "Calzada Olivar de los Padres",
		"Número": "921",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "64",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "13080.07",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "217.6",
		"Litros de agua": "32640",
		"Número de autos por construcción": "40.96",
		"Latitud": "19.3341645",
		"Longitud": "-99.230625000000003"
	},
	{
		"id": "76",
		"Colonia": "Olivar de los Padres",
		"Calle": "Calzada Olivar de los Padres",
		"Número": "1176",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "6",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "20.399999999999999",
		"Litros de agua": "3060",
		"Número de autos por construcción": "3.84",
		"Latitud": "19.3341645",
		"Longitud": "-99.230625000000003"
	},
	{
		"id": "77",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "970",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "6",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "20.399999999999999",
		"Litros de agua": "3060",
		"Número de autos por construcción": "3.84",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "78",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "991",
		"Uso de Suelo": "Habitacional ",
		"Fecha de denuncia": "23-Jun-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "79",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "720",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "12-Aug-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "80",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida de las Torres",
		"Número": "805",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "850",
		"Número de niveles de la construcción": "20",
		"Superficie m2": "11996.27",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "5",
		"Especificaciones": "S/D",
		"Población aproximada": "2890",
		"Litros de agua": "433500",
		"Número de autos por construcción": "544",
		"Latitud": "19.330923991829302",
		"Longitud": "-99.247781094773202"
	},
	{
		"id": "81",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "393",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "18-Oct-16",
		"Número de viviendas": "46",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "156.4",
		"Litros de agua": "23460",
		"Número de autos por construcción": "29.44",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "82",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "444",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "5",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "83",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "810",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "14",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "47.6",
		"Litros de agua": "7140",
		"Número de autos por construcción": "8.9600000000000009",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "84",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "979",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "85",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "985",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "33",
		"Número de niveles de la construcción": "3",
		"Superficie m2": "3025",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "43",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "112.2",
		"Litros de agua": "16830",
		"Número de autos por construcción": "21.12",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "86",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida de las Torres",
		"Número": "360",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "41",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "139.4",
		"Litros de agua": "20910",
		"Número de autos por construcción": "26.240000000000002",
		"Latitud": "19.330923991829302",
		"Longitud": "-99.247781094773202"
	},
	{
		"id": "87",
		"Colonia": "Tetelpan",
		"Calle": "Del Moral",
		"Número": "5",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "14-Sep-16",
		"Número de viviendas": "12",
		"Número de niveles de la construcción": "3",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "3",
		"Especificaciones": "S/D",
		"Población aproximada": "40.799999999999997",
		"Litros de agua": "6120",
		"Número de autos por construcción": "7.68",
		"Latitud": "19.340540000000001",
		"Longitud": "-99.234379999999902"
	},
	{
		"id": "88",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "462",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "89",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "464",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "3",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "90",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "500",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "Trabajos de de demolición",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "91",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "421",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "3",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "92",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "535",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "93",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "1146",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "13-Sep-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "Trabajos de de demolición sin licencia",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "94",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Olivar de los Padre",
		"Número": "949",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "20-Oct-16",
		"Número de viviendas": "35",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "3880",
		"Superficie máxima de construcción m2": "4900",
		"Número de árboles talados": "150",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "119",
		"Litros de agua": "17850",
		"Número de autos por construcción": "22.400000000000002",
		"Latitud": "19.34027",
		"Longitud": "-99.214479999999895"
	},
	{
		"id": "95",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "669",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "21-Oct-16",
		"Número de viviendas": "184",
		"Número de niveles de la construcción": "7",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "110",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "625.6",
		"Litros de agua": "93840",
		"Número de autos por construcción": "117.76",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "96",
		"Colonia": "Olivar de los Padres",
		"Calle": "Rómulo O´Farril ",
		"Número": "570",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "21-Oct-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "2",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "2",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.3416516903672",
		"Longitud": "-99.206134992688902"
	},
	{
		"id": "97",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "921",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "14-Nov-16",
		"Número de viviendas": "64",
		"Número de niveles de la construcción": "4",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "217.6",
		"Litros de agua": "32640",
		"Número de autos por construcción": "40.96",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "98",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "446",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "14-Nov-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "No cuenta con Manifestación de Cinstrucción",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "99",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "1036",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "19-Dec-16",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "Trabajos de demolición",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "100",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "818",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "11-Oct-17",
		"Número de viviendas": "28",
		"Número de niveles de la construcción": "7",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "95.2",
		"Litros de agua": "14280",
		"Número de autos por construcción": "17.920000000000002",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "101",
		"Colonia": "Olivar de los Padres",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5578",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "11-Mar-18",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "S/D",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338205500000001",
		"Longitud": "-99.244849500000001"
	},
	{
		"id": "102",
		"Colonia": "Olivar de los Padres",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5884",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "11-Apr-18",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "S/D",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.338205500000001",
		"Longitud": "-99.244849500000001"
	},
	{
		"id": "103",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "1036",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "3-Dec-18",
		"Número de viviendas": "300",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "S/D",
		"Especificaciones": "S/D",
		"Población aproximada": "1020",
		"Litros de agua": "153000",
		"Número de autos por construcción": "192",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "104",
		"Colonia": "Olivar de los Padres",
		"Calle": "Avenida Toluca",
		"Número": "1027",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "3-Dec-18",
		"Número de viviendas": "60",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "S/D",
		"Especificaciones": "S/D",
		"Población aproximada": "204",
		"Litros de agua": "30600",
		"Número de autos por construcción": "38.4",
		"Latitud": "19.341144",
		"Longitud": "-99.206624249999905"
	},
	{
		"id": "105",
		"Colonia": "Alcantarilla",
		"Calle": "Camino al Desierto de los Leones",
		"Número": "5547",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "15-Jul-16",
		"Número de viviendas": "233",
		"Número de niveles de la construcción": "11",
		"Superficie m2": "27525.23",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "Licencia de demolición ",
		"Población aproximada": "792.19999999999993",
		"Litros de agua": "118829.99999999999",
		"Número de autos por construcción": "149.12",
		"Latitud": "19.335616252979701",
		"Longitud": "-99.249455963147597"
	},
	{
		"id": "106",
		"Colonia": "Alcantarilla",
		"Calle": "Cerrada Tlahuicole",
		"Número": "22",
		"Uso de Suelo": "Habitacional",
		"Fecha de denuncia": "15-Jul-16",
		"Número de viviendas": "100",
		"Número de niveles de la construcción": "12",
		"Superficie m2": "2602",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "2",
		"Especificaciones": "S/D",
		"Población aproximada": "340",
		"Litros de agua": "51000",
		"Número de autos por construcción": "64",
		"Latitud": "19.338947999999998",
		"Longitud": "-99.244363499999906"
	},
	{
		"id": "107",
		"Colonia": "Alcantarilla",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "5547",
		"Uso de Suelo": "Habitacional con comercio",
		"Fecha de denuncia": "31-Jul-17",
		"Número de viviendas": "233",
		"Número de niveles de la construcción": "11",
		"Superficie m2": "27525",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "Si",
		"Niveles de construcción permitidos": "4",
		"Especificaciones": "S/D",
		"Población aproximada": "792.19999999999993",
		"Litros de agua": "118829.99999999999",
		"Número de autos por construcción": "149.12",
		"Latitud": "19.336817978254398",
		"Longitud": "-99.248587147867099"
	},
	{
		"id": "108",
		"Colonia": "Alcantarilla",
		"Calle": "Calzada Desierto de los Leones ",
		"Número": "1396",
		"Uso de Suelo": "S/D",
		"Fecha de denuncia": "18-Oct-18",
		"Número de viviendas": "S/D",
		"Número de niveles de la construcción": "S/D",
		"Superficie m2": "S/D",
		"Superficie máxima de construcción m2": "S/D",
		"Número de árboles talados": "S/D",
		"Fusión de Predios": "No",
		"Afectaciones Ambientales/Barrancas": "No",
		"Niveles de construcción permitidos": "S/D",
		"Especificaciones": "S/D",
		"Población aproximada": "S/D",
		"Litros de agua": "S/D",
		"Número de autos por construcción": "S/D",
		"Latitud": "19.336817978254398",
		"Longitud": "-99.248587147867099"
	},
]